(require 'yasnippet)

(defun load-yas-expand ()
  (interactive)
  (yas-global-mode 1)
  (yas-expand))
(defun load-yas-new-snippet ()
  (interactive)
  (yas-global-mode 1)
  (yas-new-snippet))
(defun load-yas-visit-snippet-file ()
  (interactive)
  (yas-global-mode 1)
  (yas-visit-snippet-file))
(defun load-yas-insert-snippet ()
  (interactive)
  (yas-global-mode 1)
  (yas-insert-snippet))

(provide 'yasnippet-plus)
