[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'machakann/vim-textobj-delimited'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'rust-lang/rust.vim'
lazy = 1
on_ft = 'rust'

[[plugins]]
repo = 'Shougo/denite.nvim'
lazy = 1
on_cmd = 'Denite'
hook_add = '''
	nnoremap <silent> <C-b> :<C-u>Denite buffer<CR>
	nnoremap <silent> <C-d> :<C-u>Denite -default-action='delete' buffer<CR>
	nnoremap <silent> <C-f> :<C-u>Denite filec<CR>
	nnoremap <silent> <C-r> :<C-u>Denite file_old<CR>
	nnoremap <silent> <C-h> :<C-u>Denite help<CR>
	nnoremap <silent> <A-x> :<C-u>Denite command<CR>
'''
hook_post_source = '''
	call denite#custom#map('insert', '<UP>', '<denite:move_to_previous_line>', 'noremap')
	call denite#custom#map('insert', '<Down>', '<denite:move_to_next_line>', 'noremap')
	call denite#custom#map('insert', '<PageDown>', '<denite:scroll_page_forwards', 'noremap')
	call denite#custom#map('insert', '<PageUp>', '<denite:scroll_page_backwards', 'noremap')
	call denite#custom#map('insert', '<C-b>', '<denite:move_caret_to_one_word_left>', 'noremap')
	call denite#custom#map('insert', '<C-w>', '<denite:move_caret_to_one_word_right>', 'noremap')
	call denite#custom#map('insert', '<C-d>', '<denite:delete_word_before_care>t', 'noremap')
	call denite#custom#map('insert', '<C-a>', '<denite:toggle_select_all>', 'noremap')

'''
[[plugins]]
repo = 'Shougo/deoplete.nvim'
lazy = 1
on_event = 'InsertEnter'
hook_add = '''
	let g:deoplete#enable_at_startup = 1
	let g:deoplete#max_list = 7
'''

[[plugins]]
repo = 'Shougo/neco-vim'
lazy = 1
on_ft = 'vim'

[[plugins]]
repo = 'zchee/deoplete-zsh'
lazy = 1
on_ft = 'zsh'

[[plugins]]
repo = 'zchee/deoplete-jedi'
lazy = 1
on_ft = 'python'

[[plugins]]
repo = 'eagletmt/neco-ghc'
lazy = 1
on_ft = 'haskell'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
	let g:openbrowser_browser_commands = [
		\{ "name": "firefox"
		\, "args": ["{browser}", "{uri}"] }]

	map <Space>/ <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = '''
	let g:sandwich_no_default_key_mappings = 1
	let g:operator_sandwich_no_default_key_mappings = 1
	let g:textobj_sandwich_no_default_key_mappings = 1

	omap ib <Plug>(textobj-sandwich-auto-i)
	xmap ib <Plug>(textobj-sandwich-auto-i)
	omap ab <Plug>(textobj-sandwich-auto-a)
	xmap ab <Plug>(textobj-sandwich-auto-a)
	omap if <Plug>(textobj-sandwich-query-i)
	xmap if <Plug>(textobj-sandwich-query-i)
	omap af <Plug>(textobj-sandwich-query-a)
	xmap af <Plug>(textobj-sandwich-query-a)

	map <silent> s <Plug>(operator-sandwich-add)
	nmap <silent> <Space>s <Plug>(operator-sandwich-add)iw
	nmap <silent> <Space>S <Plug>(operator-sandwich-add)iW
	nmap <silent> S <Home><Plug>(operator-sandwich-add)<End>

	nmap <silent> cs <Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)
	nmap <silent> ds <Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)

	xmap <silent> C <Plug>(operator-sandwich-replace)
	xmap <silent> D <Plug>(opecator-sandwich-delete)

	nmap . <Plug>(operator-sandwich-dot)
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
lazy = 0
hook_add = '''
	let g:neosnippet#disable_runtime_snippets = { '_' : 1 }
	let g:neosnippet#snippets_directory = expand('$XDG_CONFIG_HOME/nvim/snips')

	nnoremap <Bar>s :NeoSnippetEdit<CR>
	imap <C-Tab> <Plug>(neosnippet_expand_or_jump)
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
	let g:tcommentMaps = 0
	nmap ; <Plug>TComment_<c-_><c-_>
'''
