"a: selocted text in visual mode is automatically yanked into X11 primary register
"c: use console dialog instead of  popup dialog
"e: use guitavline instead of console tabline
"r: right side  vertical scroll bar
"b: bottom horizontal scroll bar
set guioptions=ac
set guifont=monospace\ 11
"show non-ascii sign as full-width
set ambiwidth=double
