[[plugins]]
repo = 'Shougo/dein.vim'

#[[plugins]]
#repo = 'garbas/vim-snipmate'
#hook_add = '''
#'''

[[plugins]]
repo = 'vifm/neovim-vifm'

[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = '''
	let g:sandwich_no_default_key_mappings = 1
	let g:operator_sandwich_no_default_key_mappings = 1
	let g:textobj_sandwich_no_default_key_mappings = 1
'''

[[plugins]]
repo = 'machakann/vim-textobj-delimited'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
