(autoload 'evil-change-whole-word "evil-operate-word" "" t)
(autoload 'evil-change-whole-WORD "evil-operate-word" "" t)
(autoload 'evil-delete-whole-word "evil-operate-word" "" t)
(autoload 'evil-delete-whole-WORD "evil-operate-word" "" t)
(autoload 'evil-yank-whole-word "evil-operate-word" "" t)
(autoload 'evil-yank-whole-WORD "evil-operate-word" "" t)
(autoload 'evil-upcase-whole-word "evil-operate-word" "" t)
(autoload 'evil-downcase-whole-word "evil-operate-word" "" t)

(provide 'autoload-evil-operate-word)
