(autoload #'evil-change-whole-word "evil-plus" "" t)
(autoload #'evil-change-whole-WORD "evil-plus" "" t)
(autoload #'evil-delete-whole-word "evil-plus" "" t)
(autoload #'evil-delete-whole-WORD "evil-plus" "" t)
(autoload #'evil-backward-delete-line "evil-plus" "" t)
(autoload #'evil-yank-whole-word "evil-plus" "" t)
(autoload #'evil-yank-whole-WORD "evil-plus" "" t)
(autoload #'evil-upcase-whole-word "evil-plus" "" t)
(autoload #'evil-downcase-whole-word "evil-plus" "" t)
(autoload #'evil-copy-word-from-above "evil-plus" "" t)
(autoload #'evil-copy-word-from-below "evil-plus" "" t)

(autoload #'evil-insert-word "evil-plus" "" t)
(autoload #'evil-insert-WORD "evil-plus" "" t)
(autoload #'evil-append-word "evil-plus" "" t)
(autoload #'evil-append-WORD "evil-plus" "" t)
(autoload #'evil-split "evil-plus" "" t)
(autoload #'evil-backward-substitute "evil-plus" "" t)
(autoload #'evil-join-comment "evil-plus" "" t)

(autoload #'evil-escape "evil-plus" "" t)
(autoload #'evil-use-clipboard "evil-plus" "" t)
(autoload #'evil-repeat-macro "evil-plus" "" t)
(autoload #'evil-rectangle-number-lines "evil-plus" "" t)
(autoload #'evil-save-and-delete-buffer "evil-plus" "" t)

(autoload #'evil-ex-interactive-substitute "evil-plus" "" t)

(provide 'evil-plus-autoload)
