# Test for an interactive shell.  There is no need to set anything
[[ $- != *i* ]] && return

[ -z $TMPDIR ] && TMPDIR=/tmp
HISTFILE=$TMPDIR/bash_history-$UID

alias_file=$XDG_CONFIG_HOME/sh-common/alias.sh
[ -e $alias_file ] && . $alias_file
unset alias_file
